export const PROPER_CROP_TO_IMG: Partial<Record<string, string>> = {
	Cactus: '/images/crops/cactus.png',
	Carrot: '/images/crops/carrot.png',
	'Cocoa Beans': '/images/crops/cocoa.png',
	Melon: '/images/crops/melon.png',
	Mushroom: '/images/crops/mushroom.png',
	'Nether Wart': '/images/crops/netherwart.png',
	Potato: '/images/crops/potato.png',
	Pumpkin: '/images/crops/pumpkin.png',
	'Sugar Cane': '/images/crops/sugarcane.png',
	Wheat: '/images/crops/wheat.png',
};

export const CROP_TO_HEX: Partial<Record<string, string>> = {
	wheat: '#d5da45',
	melon: '#bb170b',
	cactus: '#3b5b1d',
	pumpkin: '#a0560b',
	carrot: '#ff8e09',
	potato: '#e9ba62',
	cane: '#82a859',
	sugarcane: '#82a859',
	wart: '#5c151a',
	netherwart: '#5c151a',
	mushroom: '#725643',
	cocoa: '#61381d',
	Cactus: '#3b5b1d',
	Carrot: '#ff8e09',
	'Cocoa Beans': '#61381d',
	Melon: '#bb170b',
	Mushroom: '#725643',
	'Nether Wart': '#5c151a',
	Potato: '#e9ba62',
	Pumpkin: '#a0560b',
	'Sugar Cane': '#82a859',
	Wheat: '#d5da45',
};
